### PR TITLE
 make recursion through function calls optional 

### PR DESCRIPTION
**Pull request by simeonschaub**
to address some of the points brought up in jw3126/ArgCheck.jl#33
cc: @tkf, @jw3126

### CODE REVIEW

**Comment by simeonschaub** [comment]
# [Codecov](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=h1) Report
> Merging [#13](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=desc) into [master](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/commit/862436bd23f980623152b6aa824222c4acde2fc4&el=desc) will **increase** coverage by `2.56%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master       #13      +/-   ##
===========================================
+ Coverage   97.43%   100.00%   +2.56%     
===========================================
  Files           1         1              
  Lines          39        44       +5     
===========================================
+ Hits           38        44       +6     
+ Misses          1         0       -1     
```


| [Impacted Files](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/OptionalArgChecks.jl](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13/diff?src=pr&el=tree#diff-c3JjL09wdGlvbmFsQXJnQ2hlY2tzLmps) | `100.00% <0.00%> (+2.56%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=footer). Last update [862436b...ba7a740](https://codecov.io/gh/simeonschaub/OptionalArgChecks.jl/pull/13?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by tkf** [comment]
Does this handle keyword arguments?  IIUC you need to handle keyword sorter differently than normal functions?  Or does IRTools handle this already?

**Comment by simeonschaub** [comment]
That's a valid point, @tkf. It seems like IRTools doesn't recurse into keyword argument functions. I should add a warning, but that's definitely a problem with IRTools

**Comment by tkf** [comment]
Yeah, it'd be nice to document it if it's difficult to workaround this issue.

FYI, inbound checking also has a similar problem: https://github.com/JuliaLang/julia/issues/30411

**Comment by simeonschaub** [comment]
I added a warning in the docs now, which should hopefully make people aware of the issue

**Pull request merged**
