### PR TITLE
Support Julia v1.0+

### PR DESCRIPTION
**Pull request by singularitti**
The current code only supports up to v1.4.

### CODE REVIEW

**Comment by singularitti** [comment]
I was using it in [my code](https://github.com/MineralsCloud/QuasiHarmonicApprox.jl/blob/fbdb027f3247e1a1c73c73aa39b0b276a2f86467/Project.toml#L11).

**Comment by PallHaraldsson** [comment]
FYI: I tried it on 1.8.1, and I get a segfault in part of the tests, so there's a reason for only supporting up to 1.4. I don't know what it is, but I filed an issue at Julialang. The package was experimental, so I guess used experimental Julialang code.

**Comment by PallHaraldsson** [comment]
FYI: Not likely to be fixed (since not wanted to be fixed here where the problem is):
https://github.com/JuliaLang/julia/issues/46727#issuecomment-1244611269

I'm still curious if it can be fixed and if even I could do it. The segfault seems like it might be more general than this package.

**Comment by singularitti** [comment]
Sad. Probably I will use [`ToggleableAsserts.jl`](https://github.com/MasonProtter/ToggleableAsserts.jl).

**Pull request closed without merging**
